config/routes.rb
QuoterRails::Application.routes.draw do
  resources :users
  
  root :to => 'users#index'
  post 'login' => 'users#login', as: :session_init
  get 'logout' => 'users#logout'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  has_many :quotes_products
  has_many :quotes_products, through: :quotes
  has_many :products, through: :quotes_products
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :products_quotes
  has_many :quotes, through: :products_quotes
  has_many :customers, through: :quotes
  belongs_to :user
end

app/models/products_quote.rb
class ProductsQuote < ActiveRecord::Base
  belongs_to :product
  belongs_to :quote
  belongs_to :customer
  belongs_to :user
  
end

app/models/quote.rb
class Quote  < ActiveRecord::Base
  belongs_to :user
  belongs_to :customer
  has_many :quotes_products
  has_many :products, through: :quotes_products
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :quotes
  has_many :customers, through: :quotes
  has_many :quotes_products
  has_many :quotes_products, through: :quotes
  has_many :products, through: :quotes_products
  has_many :products

  validates :name, presence: true, uniqueness: true
  validates :password_digest, presence: true
  attr_accessible :name, :first_name, :last_name, :status, :password_digest, :email, :password

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @user = User.new
    render :index
  end

  def login
    @user = User.find_by_username(params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = ['Invalid username or password.']

      redirect_to root_path
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuoterRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<ul>
  <%= form_for @user do |f| %>
    <li>
      <%= f.email_field :first_name, placeholder: "First Name"  %>
    </li>
    <li>
      <%= f.email_field :last_name, placeholder: "Last Name"  %>
    </li>
    <li>
      <%= f.email_field :name, placeholder: "Username"  %>
    </li>
    <li>
      <%= f.email_field :email, placeholder: "Email"  %>
    </li>
    <li>
      <%= f.password_field :password, placeholder: "Password"  %>
    </li>
    <li><%= f.submit 'Signup' %></li>
  <% end %>
</ul>

app/views/users/_form_signin.html.erb
<ul>
  <%= form_tag session_init_path, :method => :post do %>
    <li>
      <%= email_field_tag :name, nil, placeholder: "Name" %>
    </li>
    <li>
      <%= password_field_tag :password, nil, placeholder: "Password"  %>
    </li>
    <li><%= submit_tag 'Signin' %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h2>Signin</h2>
<%= render 'form_signin' %>

<%= link_to "Signup", new_user_path %>

app/views/users/new.html.erb
<h2>Signup</h2>
<%= render 'form' %>
<%= link_to "Signin", root_path %>